"""empty message

Revision ID: 5edb12ed27a2
Revises: 9dc3e0b81bec
Create Date: 2024-03-14 12:37:09.710102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5edb12ed27a2'
down_revision = '9dc3e0b81bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('text_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('images_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'image_text', ['text_id'], ['id'])
        batch_op.drop_column('detail')
        batch_op.drop_column('author_id')
        batch_op.drop_column('create_time')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('author_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('detail', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('images_ibfk_1', 'user', ['author_id'], ['id'])
        batch_op.drop_column('text_id')
        batch_op.drop_column('filename')

    op.drop_table('image_text')
    # ### end Alembic commands ###
