"""empty message

Revision ID: 879ee010d815
Revises: 5edb12ed27a2
Create Date: 2024-03-25 16:24:12.123859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879ee010d815'
down_revision = '5edb12ed27a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
