"""empty message

Revision ID: ed7b04032374
Revises: a8fa6972339d
Create Date: 2024-03-10 19:48:15.562933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed7b04032374'
down_revision = 'a8fa6972339d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.drop_index('phone')
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
